# Chap 4 的numpy套件(numeric python)
## 為什麼需要numpy?
* numpy由C撰寫，速度快python 10-1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [1]:
a_list=[1,2,3,4,5]

#若沒有特別處理的話，python將會視為字串
#並且重複印三次
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#numpy套件的ndarray型態，提供element-wise的操作

#套用「numpy」將之名稱改為「np」
import numpy as np

#a盛裝「numpy」的資料陣列結構
a = np.array([1,2,3,4,5])

#將a內的值乘三
print(a*3)

[ 3  6  9 12 15]


In [4]:
#宣告，前面宣告過可「免宣告」
a = np.array([1,2,3,4,5])

#列印
print(type(a))

#印出ndarry的形狀，可以視為有多少筆資料
print(a.shape)

#印出資料的型態，是string還是int...
print(a.dtype)

#印出維度，是幾維陣列
print(a.ndim)

<class 'numpy.ndarray'>
(5,)
int32
1


In [10]:
#套用「numpy」將之改名為「np」
#與MySQL語法相似
''' list 可以動態存異質資料
    Numpy 具備平行處理的能力，可以將操作動作一次套用在大型陣列上'''
import numpy as np

z = np.zeros(6)
print(z)

#「np.empty(幾維陣列,幾行(沒寫預設為1),幾筆資料)」產生出2維陣列裡面有四筆資料
print("-----產生出2維陣列裡面有四筆資料-----")
print(np.empty((2,4)))

#「np.empty(幾維陣列,幾行(沒寫預設為1),幾筆資料)」產生出4維陣列裡面有二筆資料
print("-----產生出4維陣列裡面有二筆資料-----")
print(np.empty((4,4,2)))

#「np.empty(幾維陣列(沒寫預設為1),幾行(沒寫預設為1),幾筆資料)」產生出1維陣列裡面有三筆資料
print("-----產生出1維陣列裡面有三筆資料-----")
print(np.empty(3))

#「np.arange(10)」從0開始到10-1，間隔1

print("-----從0開始到10-1，間隔1-----")
print(np.arange(10))

#從1開始到20-1，間隔2

print("-----從1開始到20-1，間隔2-----")
print(np.arange(1,20,2))

[0. 0. 0. 0. 0. 0.]
-----產生出2維陣列裡面有四筆資料-----
[[0.000e+000 0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 6.364e-321 0.000e+000 0.000e+000]]
-----產生出4維陣列裡面有二筆資料-----
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
-----產生出1維陣列裡面有三筆資料-----
[1.14877609e-311 0.00000000e+000 1.02360867e-306]
-----從0開始到10-1，間隔1-----
[0 1 2 3 4 5 6 7 8 9]
-----從1開始到20-1，間隔2-----
[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
#上面已經import過，免再次import
#宣告「my_array」盛裝「numpy.array(10)」
my_array = np.arange(10)

#從0開始印出10筆資料
print(my_array)

#「my_array」為幾維陣列(1維為0)，算法與陣列相同
print(my_array[0])

#「my_array[0:5]」印出1維陣列從0到5
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

### 2維資料取值

In [22]:
#宣告「my_2d_array」盛裝「np.array([np.arange(0,5), np.arange(5,10)])」
#套用numpy的array(排列)格式裝「0-5」從0開始到5-1、「5-10」從5開始到10-1
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)],) #「array」陣列「arage」範圍

#印出「my_2d_array」
print(my_2d_array)

#印出「my_2d_array[1,:]」[1第一陣列 ,的 :全部]，陣列算法與JAVA相同
print(my_2d_array[1,:])

#印出「my_2d_array[:,1]」[:全部 ,的 1第一陣列]，陣列算法與JAVA相同
print(my_2d_array[:,1])


[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]


In [26]:
#宣告「my_array」盛裝「np.arange(0,10)」numpy格式範圍從0-10每次+1，共10筆資料
my_array = np.arange(0,10)

#印出「my_array」
print(my_array)

#印出「my_array」的形狀「.shape」，因宣告時共10筆(1維陣列)，故顯示10
print(my_array.shape)

#宣告「my_ad_array」盛裝被改變的「my_array」形狀
#「my_array.reshape(2,5)」印出兩行，一行五筆資料
my_2d_array = my_array.reshape(2,5)

#印出「my_2d_array」
print(my_2d_array)

#印出「numpy」的0-150每次+1，並且改變它的形狀，每行010筆，共15行
print((np.arange(0,150).reshape(15,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]


### numpy的空值nan

In [28]:
#宣告「b」盛裝「np.array([56, 8, 19, 14, np.nan])」
#「numpy」的「array」可以自行輸入要的值
#「numpy.nan」自私為「numpy的nan空值」
b = np.array([56, 8, 19, 14, np.nan])

#印出「b」
print(b)

[56.  8. 19. 14. nan]
